- name: create the software user
  user:
      name: "{{ user_name }}"
      group: users

- name: make the software user able to install osdeps using APT
  template:
      src: files/sudoers.j2
      dest: "/etc/sudoers.d/{{ user_name }}_osdeps_access"
      validate: '/usr/sbin/visudo -cf %s'

