- name: 'Install Chrony'
  import_tasks: tasks/chrony.yml
  become: true
- name: 'Setup the GPIOs'
  import_tasks: tasks/gpios.yml
  tags:
      - gpios
  become: true
- name: 'Setup device links and drivers'
  import_tasks: tasks/devices.yml
  become: true
      
- name: 'Setup the system to allow realtime execution'
  become: true
  copy:
      src: files/etc/security/limits.d/rock-realtime.conf
      dest: /etc/security/limits.d/rock-realtime.conf
      mode: 0644
      owner: root
      group: root

- name: 'Copy the sysctl file to set MQ limits in /proc'
  become: true
  copy:
      src: files/etc/sysctl.d/10-posix_mq.conf
      dest: /etc/sysctl.d/10-posix_mq.conf
      mode: 0644
      owner: root
      group: root

- name: 'Apply sysctl changes'
  become: true
  shell: "sysctl --system"
