prefer_indep_over_os_packages: false
osdeps_mode: all
manifest_name: manifest.navbox
GITORIOUS: http,ssh
GITORIOUS_ROOT: https://git.gitorious.org
GITORIOUS_PUSH_ROOT: 'git@gitorious.org:'
GITORIOUS_PRIVATE_ROOT: 'git@gitorious.org:'
GITHUB: http,ssh
GITHUB_ROOT: https://github.com
GITHUB_PUSH_ROOT: 'git@github.com:'
GITHUB_PRIVATE_ROOT: 'git@github.com:'
ROCK_SELECTED_FLAVOR: master
ROCK_FLAVOR: master
ROCK_BRANCH: master
cxx11: false
typelib_cxx_loader: castxml
USE_OCL: false
rtt_target: gnulinux
rtt_corba_implementation: omniorb

